name: Kartkowka Workflow

on:
  push:
  workflow_dispatch: {}

jobs:
  build_image:
    name: Build Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v5

      - name: Build Image
        run: docker build -t kartkowka .

      - name: Write Summary
        if: always()
        run: |
          echo "event: ${{ github.event_name }}" >> "$GITHUB_STEP_SUMMARY"
          echo "ref: ${{ github.ref }}" >> "$GITHUB_STEP_SUMMARY"
          echo "commit_hash: ${{ github.sha }}" >> "$GITHUB_STEP_SUMMARY"
